# RCP Server Configuration

# Server address to bind to
address = "0.0.0.0"

# Server port to listen on
port = 8716

[tls]
enabled = false
cert_path = "cert.pem"
key_path = "key.pem"

[auth]
required = true
psk = "customkey"
allowed_clients = []
# Grant permissions to services
permissions = ["display", "input", "audio", "clipboard", "file-transfer", "app", "app:launch", "*"]

[session]
max_sessions = 10
timeout_secs = 3600
allow_resumption = true

[application]
# Allow all default applications
allowed_apps = ["default:*"]
denied_apps = []
allow_elevated = false
work_dir = "./apps"

# Service permissions
[services]
# Enable all services including app service
enabled = ["display", "input", "audio", "clipboard", "file-transfer", "app"]