# RCP Project - Cargo Configuration
# This configuration handles native dependencies using bindgen properly

[env]
# Force zstd-sys to build from source and avoid pkg-config
ZSTD_SYS_USE_PKG_CONFIG = "0"
ZSTD_SYS_FORCE_FROM_SOURCE = "1"

# Use pre-generated bindings for zstd-sys
ZSTD_SYS_USE_BINDGEN = "0"
ZSTD_SYS_ZSTD_SRC_PATH = "./target/zstd-src"

# AWS-LC system configuration to avoid CMake requirement
AWS_LC_SYS_STATIC = "1"
AWS_LC_SYS_USE_SHARED = "0"
AWS_LC_SYS_VENDORED = "1"

# Override the build and test environment configuration
[build]
# Use the vscode toolchain by default
target-dir = "target"
rustflags = ["-C", "link-arg=-s"]

# Windows-specific settings
[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-feature=+crt-static"]