[package]
name = "rcp-examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rcp-client = { path = "../rcp-client" }
rcp-core = { path = "../rcp-core" }
tokio = { version = "1.44.2", features = ["full"] }
env_logger = "0.11.8"
uuid = { version = "1.16.0", features = ["v4"] }
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[[bin]]
name = "client-example"
path = "src/client_example.rs"

[[bin]]
name = "app-launch-example"
path = "src/app_launch_example.rs"

[build-dependencies]
# Add any build dependencies needed