name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt
    
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        shared-key: "rcp-${{ runner.os }}"
    
    - name: Check code formatting
      run: cargo fmt --all -- --check
    
    - name: Run tests
      run: cargo test --all-targets --all-features --verbose
    
    - name: Auto-fix simple warnings with clippy
      run: cargo clippy --fix --all-targets --all-features --allow-dirty --allow-staged
      continue-on-error: true
    
    - name: Run clippy with warnings as errors
      run: cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Build docs
      run: cargo doc --no-deps --verbose