name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.2.0)'
        required: true

# Add permissions block for GITHUB_TOKEN
permissions:
  contents: write
  discussions: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create_release:
    name: Create Release
    # Only run when a tag is pushed or on manual workflow dispatch
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          # Extract version from tag name
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
        echo "Using version: $(cat $GITHUB_OUTPUT | grep version | cut -d= -f2)"
    
    - name: Validate version format
      run: |
        VERSION=$(cat $GITHUB_OUTPUT | grep version | cut -d= -f2)
        if ! [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$ ]]; then
          echo "Invalid version format: $VERSION"
          echo "Version must be in format v1.2.3 or v1.2.3-alpha"
          exit 1
        fi
    
    - name: Generate release notes
      id: release_notes
      run: |
        # Get previous tag for comparison
        prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$prev_tag" ]; then
          prev_tag=$(git rev-list --max-parents=0 HEAD)  # First commit
          echo "No previous tag, using first commit as reference: $prev_tag"
        fi
        
        # Create a release notes file with sections for features, fixes, etc.
        echo "## Changes in ${{ steps.get_version.outputs.version }}" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        
        # Features
        echo "### Features" >> RELEASE_NOTES.md
        git log $prev_tag..HEAD --pretty=format:"- %s" --grep="^feat" | grep -v "^$" | sort >> RELEASE_NOTES.md || echo "- No new features in this release" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        
        # Bug fixes
        echo "### Bug Fixes" >> RELEASE_NOTES.md
        git log $prev_tag..HEAD --pretty=format:"- %s" --grep="^fix" | grep -v "^$" | sort >> RELEASE_NOTES.md || echo "- No bug fixes in this release" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        
        # Improvements
        echo "### Improvements" >> RELEASE_NOTES.md
        git log $prev_tag..HEAD --pretty=format:"- %s" --grep="^improve\|^refactor\|^perf" | grep -v "^$" | sort >> RELEASE_NOTES.md || echo "- No improvements in this release" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        
        # Documentation changes
        echo "### Documentation" >> RELEASE_NOTES.md
        git log $prev_tag..HEAD --pretty=format:"- %s" --grep="^docs" | grep -v "^$" | sort >> RELEASE_NOTES.md || echo "- No documentation changes in this release" >> RELEASE_NOTES.md
        
        cat RELEASE_NOTES.md
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        name: RCP ${{ steps.get_version.outputs.version }}
        tag_name: ${{ steps.get_version.outputs.version }}
        body_path: RELEASE_NOTES.md
        draft: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    name: Build for ${{ matrix.platform }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            deps_cmd: >
              sudo apt-get update && 
              sudo apt-get install -y libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config
            archive_ext: tar.gz
          - platform: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            deps_cmd: choco install pkgconfiglite
            archive_ext: zip
          - platform: macos
            os: macos-latest
            target: x86_64-apple-darwin
            deps_cmd: brew install pkg-config
            archive_ext: tar.gz
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Check for cached build from CI workflow to speed up builds
    - name: Check for cached build
      id: cached-build
      uses: actions/cache@v3
      with:
        path: target/${{ matrix.target }}/release
        key: rcp-${{ matrix.platform }}-release-${{ hashFiles('**/Cargo.lock', '**/*.rs') }}
        restore-keys: |
          rcp-${{ matrix.platform }}-release-
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        components: clippy, rustfmt
    
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        shared-key: "rcp-${{ matrix.platform }}-release-${{ hashFiles('**/Cargo.lock') }}"
        cache-on-failure: true
    
    - name: Install dependencies for platform
      if: matrix.deps_cmd != ''
      run: ${{ matrix.deps_cmd }}
      shell: bash
    
    # Skip clippy if we have a cached build
    - name: Run Clippy
      if: steps.cached-build.outputs.cache-hit != 'true'
      run: cargo clippy --all-targets --all-features -- -D warnings
    
    # Build each component for release
    - name: Build RCP Protocol
      if: steps.cached-build.outputs.cache-hit != 'true'
      run: cargo build --release --package rcpp --target ${{ matrix.target }}
    
    - name: Build RCP Client
      if: steps.cached-build.outputs.cache-hit != 'true'
      run: cargo build --release --package rcpc --target ${{ matrix.target }}
    
    - name: Build RCP Daemon
      if: steps.cached-build.outputs.cache-hit != 'true'
      run: cargo build --release --package rcpd --target ${{ matrix.target }}
    
    # Protocol package preparation
    - name: Create Protocol Package Directory
      run: mkdir -p rcpp-pkg
      shell: bash
    
    - name: Copy Protocol Binary (Windows)
      if: matrix.platform == 'windows'
      run: |
        cp target/${{ matrix.target }}/release/rcpp.exe rcpp-pkg/rcpp.exe
        cp config.toml rcpp-pkg/config.toml
      shell: bash
    
    - name: Copy Protocol Binary (Linux/macOS)
      if: matrix.platform != 'windows'
      run: |
        cp target/${{ matrix.target }}/release/rcpp rcpp-pkg/rcpp
        cp config.toml rcpp-pkg/config.toml
      shell: bash
    
    - name: Package Protocol (Windows)
      if: matrix.platform == 'windows'
      run: Compress-Archive -Path rcpp-pkg/* -DestinationPath rcpp-windows.zip
      shell: pwsh
    
    - name: Package Protocol (Linux/macOS)
      if: matrix.platform != 'windows'
      run: tar -czf rcpp-${{ matrix.platform }}.${{ matrix.archive_ext }} -C rcpp-pkg .
      shell: bash
    
    # Client package preparation
    - name: Create Client Package Directory
      run: mkdir -p rcpc-pkg
      shell: bash
    
    - name: Copy Client Binary (Windows)
      if: matrix.platform == 'windows'
      run: |
        cp target/${{ matrix.target }}/release/rcpc.exe rcpc-pkg/rcpc.exe
      shell: bash
    
    - name: Copy Client Binary (Linux/macOS)
      if: matrix.platform != 'windows'
      run: |
        cp target/${{ matrix.target }}/release/rcpc rcpc-pkg/rcpc
      shell: bash
    
    - name: Package Client (Windows)
      if: matrix.platform == 'windows'
      run: Compress-Archive -Path rcpc-pkg/* -DestinationPath rcpc-windows.zip
      shell: pwsh
    
    - name: Package Client (Linux/macOS)
      if: matrix.platform != 'windows'
      run: tar -czf rcpc-${{ matrix.platform }}.${{ matrix.archive_ext }} -C rcpc-pkg .
      shell: bash
    
    # Daemon package preparation
    - name: Create Daemon Package Directory
      run: mkdir -p rcpd-pkg
      shell: bash
    
    - name: Copy Daemon Binary (Windows)
      if: matrix.platform == 'windows'
      run: |
        cp target/${{ matrix.target }}/release/rcpd.exe rcpd-pkg/rcpd.exe
        cp rcpd_config.toml rcpd-pkg/rcpd_config.toml
      shell: bash
    
    - name: Copy Daemon Binary (Linux/macOS)
      if: matrix.platform != 'windows'
      run: |
        cp target/${{ matrix.target }}/release/rcpd rcpd-pkg/rcpd
        cp rcpd_config.toml rcpd-pkg/rcpd_config.toml
      shell: bash
    
    - name: Package Daemon (Windows)
      if: matrix.platform == 'windows'
      run: Compress-Archive -Path rcpd-pkg/* -DestinationPath rcpd-windows.zip
      shell: pwsh
    
    - name: Package Daemon (Linux/macOS)
      if: matrix.platform != 'windows'
      run: tar -czf rcpd-${{ matrix.platform }}.${{ matrix.archive_ext }} -C rcpd-pkg .
      shell: bash
    
    # Upload all assets
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.create_release.outputs.version }}
        files: |
          rcpp-${{ matrix.platform }}.${{ matrix.archive_ext || 'zip' }}
          rcpc-${{ matrix.platform }}.${{ matrix.archive_ext || 'zip' }}
          rcpd-${{ matrix.platform }}.${{ matrix.archive_ext || 'zip' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish Release
    needs: [create_release, build]
    runs-on: ubuntu-latest
    if: ${{ !failure() && !cancelled() }}
    steps:
    - name: Update Release Status
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.create_release.outputs.version }}
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
